-- Esquema de Base de Datos para AFCademIA
-- Generado para Supabase (PostgreSQL)

-- 1. Tabla: leads (La Identidad)
-- Contiene los datos fijos del contacto. El email es la clave única.
CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    whatsapp TEXT,
    empresa_nombre TEXT,
    ciudad TEXT,
    ip_address TEXT,
    source TEXT DEFAULT 'Landing Page',
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Índice para búsquedas rápidas por email
CREATE INDEX IF NOT EXISTS idx_leads_email ON leads(email);

-- 2. Tabla: segmentacion_despacho (El Perfil)
-- Datos específicos del negocio de administración de fincas.
CREATE TABLE IF NOT EXISTS segmentacion_despacho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    num_comunidades TEXT NOT NULL, -- Valores: '1-10', '11-50', '50+'
    interes_fundae BOOLEAN DEFAULT FALSE,
    software_actual TEXT,
    objetivo_automatizacion TEXT, -- ¿Qué quieren automatizar primero?
    UNIQUE(lead_id)
);

-- 3. Tabla: flujos_embudo (El Comportamiento)
-- Registro de estados y respuestas automáticas (Make/Zapier).
CREATE TABLE IF NOT EXISTS flujos_embudo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    nombre_flujo TEXT DEFAULT 'formulario web',
    status_actual TEXT DEFAULT 'nuevo', 
    keyword_recibida TEXT,
    fecha_ultima_interaccion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    tags_proceso JSONB DEFAULT '[]'::jsonb,
    
    CONSTRAINT chk_status CHECK (status_actual IN ('nuevo', 'en_proceso', 'contactado', 'convertido', 'perdido'))
);

-- Índice para filtrar por estado
CREATE INDEX IF NOT EXISTS idx_flujos_status ON flujos_embudo(status_actual);
